version: 2.1
orbs:
  bridgecrew: bridgecrew/bridgecrew@1.0.5
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run:
          name: Install Go
          command: |
            sudo apt-get update
            sudo apt-get install -y golang
      - run:
          name: Set Go Path
          command: |
            mkdir -p /home/circleci/go/src/github.com/SeungJuLee91/go-test-by-circleci-sample
            ln -s /home/circleci/project /home/circleci/go/src/github.com/SeungJuLee91/go-test-by-circleci-sample
      - bridgecrew/install
      - bridgecrew/scan:
          directory: .
          api-key-variable: testkey
          prisma-api-url: https://api.sg.prismacloud.io
      - run: go get -v -t -d ./...
      - run: go test -v ./...
