version: 2.1
orbs:
  bridgecrew: bridgecrew/bridgecrew@1.0.5
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/python:3.8  # Python과 pip이 설치된 이미지를 사용
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run:
          name: Install Go
          command: |
            sudo apt-get update
            sudo apt-get install -y golang
      - bridgecrew/install
      - bridgecrew/scan:
          directory: .
          api-key-variable: testkey
          prisma-api-url: https://api.sg.prismacloud.io
      - run: go get -v -t -d ./...
      - run: go test -v ./...
